### ISSUE TITLE
Path normalization on Windows

### ISSUE THREAD

**Issue by stax76** [CogentRedTester/mpv-file-browser#64] opened 2022-07-08 06:47 UTC
The script uses forward slashes on Windows, which often works, but also often works not.

I noticed it here:

https://github.com/mpv-player/mpv/issues/6560

It can also be an issue for some mpv frontends and some mpv user scripts, in mpv.net, I normalize paths whenever possible.

For my use case, it's not an urgent issue, but it's likely that some user will run into it one day.

**Comment by CogentRedTester** [comment] 2022-07-08 07:00
I already normalise all slashes to `/` to ensure consistency across all paths on all platforms. Almost everything works with both forward slashes as well as backwards slashes, the only exceptions are some windows utilities like command prompt and `explorer.exe`.

I'm not exactly sure what the issue is here? The main `file-browser` script does not use any system calls so there is no risk of anything going wrong, and any addon that calls one of these applications can easily switch back to `\`. In fact [windir](https://github.com/CogentRedTester/mpv-file-browser/blob/master/addons/windir.lua) already does this.

The only case where this might be an issue is with custom keybinds, but I already provide an example of how to handle that in the example json file:
```json
    {
        "key": "Ctrl+o",
        "command": ["run", "powershell", "-command", "explorer.exe", "(( %P ).TrimEnd('/') -replace '/', '\\' )"],
        "multiselect": false
    },
    {
        "key": "Ctrl+O",
        "command": ["run", "powershell", "-command", "explorer.exe", "(( %F ).TrimEnd('/') -replace '/', '\\' )"],
        "filter": "dir",
        "multiselect": true
    },
```

Is there another issue that I'm missing?

**Comment by CogentRedTester** [comment] 2022-07-08 08:26
Is the problem that opening an item from file-browser results in forward slashes? I could perhaps see that being a problem if you're trying to maintain windows safe paths at all times. I could potentially add an option to substitute `/` for `\` when appending an item to the playlist if you think that would be useful?

**Comment by CogentRedTester** [comment] 2022-07-08 08:33
It would *only* be when appending the item to the playlist however, the rest of the script, and many addons, all assume that `/` is used, it's not viable to change that.

**Comment by CogentRedTester** [comment] 2022-07-08 11:13
Ok, I'll close the issue for now. The `substitute_backslash` option should be enough to fix any breakages in other scripts.

**Closed by CogentRedTester** 2022-07-08 11:13 UTC
Labels: enhancement

**Comment by stax76** [comment] 2022-07-08 11:36
I've enabled `substitute_backslash` and it works well, thanks for the quick responses and solutions.
